const workspace = process.env.NEXT_PUBLIC_APP_URL || "#demo";

export default function Page() {
  return <main className="supply">
    <section className="supply-hero"><div className="supply-mark" aria-hidden="true">✺</div><p className="supply-brand">CApex</p><h1>The audit workspace<br />Chartered Accountants choose.</h1><p>CApex turns Tally data into materiality-aware, audit-ready exceptions—without taking the reviewer out of the loop.</p><div className="supply-actions"><a href={workspace}>Open workspace <b>↗</b></a><a href="#workflow">How it works <b>↓</b></a></div><div className="signal-field" aria-hidden="true"><i /><i /><i /><i /><i /><i /><i /><i /><i /></div></section>
    <section className="intro" id="workflow"><p>From raw ledger to reviewed exception.</p><h2>Clear scrutiny.<br />Confident review.</h2><div className="audit-screen"><aside><b>CApex</b><span>WORKSPACE</span><strong>Meridian Manufacturing</strong><a>Findings <i>5</i></a><a>Review queue</a><a>Import batches</a></aside><article><small>SCRUTINY RUN #042</small><h3>Exception review</h3><div className="screen-finding"><em>HIGH</em><b>Gross margin movement</b><p>Gross margin moved <strong>17.3 pp</strong> against the policy threshold.</p><footer>₹ 1.84 Cr variance <span>Review required →</span></footer></div><div className="screen-row"><span>Suspense account balance <b>₹ 4.20 L</b></span><span>Opening balance continuity <b>3 ledgers</b></span></div></article></div></section>
    <section className="benefits"><p>Built for a better audit workflow.</p><h2>Focused clarity.</h2><div><article><i>✦</i><h3>Deterministic checks</h3><p>Visible rules and thresholds make every exception explainable.</p></article><article><i>✳</i><h3>Auditor control</h3><p>Review, resolve, and document the decision in the same workspace.</p></article><article><i>✺</i><h3>Period context</h3><p>Surface material movements using prior-period comparison.</p></article></div></section>
    <blockquote>“The goal is not another black box. It is a quieter, more defensible audit review.”<footer>CApex <span>— built for modern audit teams</span></footer></blockquote>
    <section className="packs"><p>One clean workspace.</p><h2>Built around the audit.</h2><div className="pack-grid"><article><small>01 — IMPORT</small><h3>Start with the ledger.</h3><p>Bring in Tally XML/XLSX data and preserve the original import batch.</p><ul><li>Immutable source batches</li><li>Consistent ledger model</li><li>Clear import history</li></ul></article><article><small>02 — SCRUTINIZE</small><h3>Find material exceptions.</h3><p>Apply explainable checks to period movement, balances, and manufacturing accounts.</p><ul><li>Visible policy thresholds</li><li>Multi-period comparison</li><li>Focused sector pack</li></ul><a href={workspace}>Open live demo <b>↗</b></a></article></div></section>
    <section className="manufacturing-mini" id="demo"><p>Manufacturing v1.</p><h2>More signal, less<br />ledger noise.</h2><div><article><small>SECTOR SUGGESTION</small><h3>Manufacturing</h3><p>GST-guided suggestion, confirmed by the auditor.</p><span>✓ Raw material movement</span><span>✓ Work-in-progress movement</span><span>✓ Finished-goods movement</span></article><article><small>POLICY</small><h3>Set the boundary.</h3><p><b>1%</b> of COGS<br />inventory tolerance</p><p><b>10 pp</b><br />gross-margin movement</p></article></div></section>
    <blockquote className="quote-light">“Every exception should show its work—and every review should leave an evidence trail.”<footer>CApex <span>— audit scrutiny workspace</span></footer></blockquote>
    <section className="faq"><p>Questions.</p><h2>Answered.</h2>{["What does CApex do?", "Does it replace audit judgement?", "Which Tally exports can I use?", "Is manufacturing scrutiny included?", "Can I retain my review notes?", "Does CApex handle GST or TDS reconciliation?", "Is public demonstration data real client data?"].map((question) => <details key={question}><summary>{question}<b>+</b></summary><p>CApex keeps the scrutiny and reviewer evidence in one clear, auditable workspace.</p></details>)}</section>
    <footer className="supply-footer"><b><span>CA</span>pex</b><p>Built for modern audit teams.</p><a href={workspace}>Open live workspace ↗</a></footer>
  </main>;
}
